# --- General options --- #
safe: false

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "http://github.phillip-kruger.com"
baseurl: ""

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: Phillip Krüger

# Short description of your site
description: Everything in it's right place

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  About Me: "about"
  Software: "https://github.com/phillip-kruger"
  
# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/images/grand_canyon_face.jpg"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
# title-img: /path/to/image

# --- Background colour/image options --- #

# By default, the navigation bar and footer have a light gray background, and the main page
# has a white background. You can specify a different background colour or a background image
# for the navigation bar, the main page, and the footer.
navbar-col: "#404040"
# navbar-img: "/images/bgimage.png"
footer-col: "#404040"
# footer-img: "/img/bgimage.png"
# page-col: "#FF0000"
# page-img: "/img/bgimage.png"

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Phillip Krüger
  email: "phillip.kruger@phillip-kruger.com"
  github: phillip-kruger
  twitter: phillipkruger
  #google-plus: +yourname   # eg. +DeanAttali or 109424658772469020925
  linkedin: phillipkruger
  #stackoverflow: yourlink  # eg. "3943160/daattali"
  #youtube: yourlink   # eg. user/daattali or channel/daattali
  
# Select which links to show in the footer
footer-links-active:
  rss: true
  facebook: false
  email: true
  twitter: true
  google-plus: false
  github: true
  reddit: false
  linkedin: true
  xing: false
  stackoverflow: false
  snapchat: false
  instagram: false
  youtube: false
  spotify: false
  telephone: false
  steam: false
  twitch: false
  yelp: false

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  google: true
  linkedin: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "www.phillip-kruger.com"

# --- Misc --- #
# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: "blog-ynt5qo8h3u"

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-106577215-1"

# Google Tag Manager ID
#gtm: ""

# Facebook App ID
# fb_app_id: ""

# Excerpt Word Length
# Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Africa/Johannesburg"
markdown: kramdown
highlighter: rouge
permalink: /post/:title/
paginate: 5

kramdown:
    input: GFM
    syntax_highlighter: rouge

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Use tags pages (not recommended if you are deploying via GitHub pages, only set to true if deploying locally with ruby)
link-tags: false

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile

# prose.io config
prose:
  rooturl: '_posts'
  media: 'image'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /nbproject
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "image"
        field:
          element: "text"
          label: "Image"
          help: "Add a thumbnail image to your post."
          placeholder: "Thumbnail"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

plugins:
  - jekyll-paginate
  - jekyll-redirect-from

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
